version: "3"
services: 
  api-server:
    image: loopback-api
    ports: 
      - "4000:3000"
    networks: 
      - loop-api
    depends_on: 
      - database
  database:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports: 
      - "5432:5432"
    networks: 
      - loop-api
    volumes: 
      - pg-data:/var/lib/postgresql/data
networks:
  loop-api:
    driver: bridge 
volumes: 
  pg-data:
    driver: local